// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE8uGOpI9WdTmc3bvUa9eDCTX-rhRahWI',
    appId: '1:53456098260:web:021e1ada6d890a3cc47c41',
    messagingSenderId: '53456098260',
    projectId: 'linnet-b7f89',
    authDomain: 'linnet-b7f89.firebaseapp.com',
    storageBucket: 'linnet-b7f89.firebasestorage.app',
    measurementId: 'G-H8BKMT3M9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRWyDMpB8Cp3wymjMw-kHJ2xDL43qGBS8',
    appId: '1:53456098260:android:fac8923d6a1f008bc47c41',
    messagingSenderId: '53456098260',
    projectId: 'linnet-b7f89',
    storageBucket: 'linnet-b7f89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcorTejX2VGwOvg0UQvD9FTNRkYCQeqYQ',
    appId: '1:53456098260:ios:d6f5113d6ba85c81c47c41',
    messagingSenderId: '53456098260',
    projectId: 'linnet-b7f89',
    storageBucket: 'linnet-b7f89.firebasestorage.app',
    iosBundleId: 'com.romashka.linnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcorTejX2VGwOvg0UQvD9FTNRkYCQeqYQ',
    appId: '1:53456098260:ios:d6f5113d6ba85c81c47c41',
    messagingSenderId: '53456098260',
    projectId: 'linnet-b7f89',
    storageBucket: 'linnet-b7f89.firebasestorage.app',
    iosBundleId: 'com.romashka.linnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE8uGOpI9WdTmc3bvUa9eDCTX-rhRahWI',
    appId: '1:53456098260:web:3f9012c6f0ec07bdc47c41',
    messagingSenderId: '53456098260',
    projectId: 'linnet-b7f89',
    authDomain: 'linnet-b7f89.firebaseapp.com',
    storageBucket: 'linnet-b7f89.firebasestorage.app',
    measurementId: 'G-TVVN79KR45',
  );
}
